root = "/home/abhijat/tmp/bench"
cooldown_sec = 10

[[dragonflies]]
# path to dragonfly, H+ means start at home directory
path = "/home/abhijat/dev/cc/dragonfly/build-dbg/dragonfly"
id = "normal-build"

[dragonflies.args]
proactor_threads = "1"
logtostderr = ""

bind = "0.0.0.0"

# ROOT+ means start at the dynamic root the runner creates
dir = "ROOT+data"

[[benchmarks]]
path = "memtier_benchmark"
id = "write-only-256-1"

[benchmarks.args]
server = "127.0.0.1"
port = "6379"
protocol = "redis"

threads = "4"
clients = "25"

requests = "allkeys"
key-minimum = "1"
key-maximum = "1000000"
key-pattern = "P:P"

ratio = "1:0"
data-size = "256"

pipeline = "1"

distinct-client-seed = ""
show-config = ""
hide-histogram = ""

json-out-file = "ROOT+mt.json"

[[benchmarks]]
path = "memtier_benchmark"
id = "write-only-256-32"

[benchmarks.args]
server = "127.0.0.1"
port = "6379"
protocol = "redis"
threads = "4"
clients = "25"
requests = "allkeys"
key-minimum = "1"
key-maximum = "1000000"
key-pattern = "P:P"
ratio = "1:0"
data-size = "256"

pipeline = "32"

distinct-client-seed = ""
show-config = ""
hide-histogram = ""

json-out-file = "ROOT+mt.json"
